accounts/urls.py
from django.urls import path

from accounts.views import (
    ClientSignUpView,
    ClientDetailView,
    ClientUpdateView,
    VendorDetailView,
    VendorUpdateView,
    VendorSignUpView,
    AdminSignUpView,
    AdminDetailView,
    AdminUpdateView,
    dashboard,
    SignUpView,
    UserListView,
    UserDetailView,
)

app_name = "accounts"

urlpatterns = [
    path("dashboard/", dashboard, name="dashboard"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("detail/<str:pk>/", UserDetailView.as_view(), name="user-detail"),
    # client urls
    path("sign-up/client/", ClientSignUpView.as_view(), name="client-signup"),
    path("profile/<str:pk>/client/", ClientDetailView.as_view(), name="client-profile"),
    path("update/<str:pk>/client/", ClientUpdateView.as_view(), name="client-update"),
    # vendor urls
    path("sign-up/vendor/", VendorSignUpView.as_view(), name="vendor-signup"),
    path("profile/<str:pk>/vendor/", VendorDetailView.as_view(), name="vendor-profile"),
    path("update/<str:pk>/vendor/", VendorUpdateView.as_view(), name="vendor-update"),
    # admin urls
    path("signup/admin/", AdminSignUpView.as_view(), name="admin-signup"),
    path("profile/<str:pk>/admin/", AdminDetailView.as_view(), name="admin-profile"),
    path("update/<str:pk>/admin/", AdminUpdateView.as_view(), name="admin-update"),
]

shop/urls.py
from django.urls import path

from shop.views import (
    ShopUpdateView,
    ShopDetailView,
    ShopListView,
    ProductDetailView,
    ProductCreateView,
    ProductListView,
    ProductUpdateView,
    ProductDeleteView,
    OrderCreateView,
    VendorOrderListView,
    ClientOrderListView,
)

app_name = "shop"

urlpatterns = [
    path("shops/", ShopListView.as_view(), name="shop-update"),
    path("update/<str:pk>/shop/", ShopUpdateView.as_view(), name="shop-update"),
    path("detail/<str:pk>/shop/", ShopDetailView.as_view(), name="shop-detail"),
    path("create/", ProductCreateView.as_view(), name="product-create"),
    path(
        "product/<str:pk>/detail/", ProductDetailView.as_view(), name="product-detail"
    ),
    path(
        "product/<str:pk>/update/", ProductUpdateView.as_view(), name="product-update"
    ),
    path(
        "product/<str:pk>/delete/", ProductDeleteView.as_view(), name="product-delete"
    ),
    path("products/", ProductListView.as_view(), name="product-list"),
    path("order/<str:pk>/", OrderCreateView.as_view(), name="create-order"),
    path("orders/", VendorOrderListView.as_view(), name="order-list"),
    path("orders/client/", ClientOrderListView.as_view(), name="client-orders"),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

from accounts.abstracts import UniversalIdModel, TimeStampedModel
from cloudinary.models import CloudinaryField
from gasdelivery.settings.base import AUTH_USER_MODEL


class User(AbstractUser, UniversalIdModel, TimeStampedModel):
    is_client = models.BooleanField(default=False)
    is_vendor = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)

    def get_full_name(self) -> str:
        return super().get_full_name()

    def get_short_name(self) -> str:
        return super().get_short_name()

    def get_username(self) -> str:
        return super().get_username()


# @receiver(post_save, sender=User)
# def create_vendor_and_shop(sender, instance, created, **kwargs):
#     if created and instance.is_vendor:
#         vendor = Vendor.objects.create(user=instance)
#         Shop.objects.create(
#             owner=instance,
#             name=f"{instance.username}'s Shop",
#             location="Default Location",
#         )


class Client(TimeStampedModel):
    user = models.OneToOneField(
        AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name="client",
    )
    image = CloudinaryField("Client Image", blank=True, null=True)
    phone_number = models.BigIntegerField(blank=True, null=True)
    location = models.CharField(max_length=1000, blank=True, null=True)

    def __str__(self) -> str:
        return self.user.username


class Vendor(TimeStampedModel):
    user = models.OneToOneField(
        AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name="vendor",
    )
    image = CloudinaryField("Vendor Images", blank=True, null=True)
    phone_number = models.BigIntegerField(blank=True, null=True)
    shop_location = models.CharField(max_length=1000, blank=True, null=True)


class Admin(TimeStampedModel):
    user = models.OneToOneField(
        AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        primary_key=True,
        related_name="admin",
    )
    image = CloudinaryField("admin_image", blank=True, null=True)

    def __str__(self) -> str:
        return self.user.username

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from accounts.models import Client, Vendor, Admin
from django.db import transaction
from django.contrib.auth import get_user_model
from shop.models import Shop

User = get_user_model()


class ClientCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            "email",
            "username",
            "first_name",
            "last_name",
            "password1",
            "password2",
        )

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_client = True
        user.save()
        Client.objects.create(user=user)
        return user


class VendorCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            "email",
            "username",
            "first_name",
            "last_name",
            "password1",
            "password2",
        )

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_vendor = True
        user.save()
        Vendor.objects.create(user=user)
        Shop.objects.create(owner=user)
        return user


class AdminCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = (
            "email",
            "username",
            "first_name",
            "last_name",
            "password1",
            "password2",
        )

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_admin = True
        user.save()
        Admin.objects.create(user=user)
        return user

accounts/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.views.generic import (
    CreateView,
    UpdateView,
    ListView,
    DetailView,
)
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import (
    LoginRequiredMixin,
    UserPassesTestMixin,
)
from django.contrib.auth import get_user_model
from django.urls import reverse_lazy

from accounts.models import Admin, Client, Vendor
from accounts.forms import ClientCreationForm, VendorCreationForm, AdminCreationForm
from shop.models import Shop, Product

User = get_user_model()


def landing(request):
    return render(request, "landing.html")


@login_required
def dashboard(request):
    client_profile = Client.objects.filter(user=request.user)
    vendor_profile = Vendor.objects.filter(user=request.user)
    vendor_shop = Shop.objects.filter(owner=request.user)
    vendor_product = Product.objects.filter(created_by=request.user)
    client_products = Product.objects.filter(availability=True)
    return render(
        request,
        "accounts/dashboard.html",
        {
            "client_profile": client_profile,
            "vendor_profile": vendor_profile,
            "vendor_shop": vendor_shop,
            "vendor_product": vendor_product,
            "client_products": client_products,
        },
    )


class SignUpView(TemplateView):
    template_name = "registration/signup.html"


class UserListView(UserPassesTestMixin, ListView):
    """admin sees all users"""

    model = User
    template_name = "users_list.html"
    paginate_by = 6

    def test_func(self):
        return self.request.user.is_staff


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = "accounts/user_detail.html"

    def get_queryset(self):
        return User.objects.filter(username=self.request.user)


# Client views
class ClientSignUpView(SuccessMessageMixin, CreateView):
    model = User
    form_class = ClientCreationForm
    template_name = "registration/signup_form.html"
    success_message = "Account Created Successfully"

    def get_context_data(self, **kwargs):
        kwargs["user_type"] = "client"
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect("accounts:dashboard")


class ClientDetailView(LoginRequiredMixin, DetailView):
    model = Client
    template_name = "accounts/user_profile.html"
    context_object_name = "client_detail"

    def get_queryset(self):
        return Client.objects.filter(user=self.request.user)


class ClientUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Client
    template_name = "accounts/user_update.html"
    success_message = "Profile Updated Successfully!"
    fields = [
        "image",
        "phone_number",
        "location",
    ]
    success_url = reverse_lazy("accounts:dashboard")

    def get_queryset(self):
        return Client.objects.filter(user=self.request.user)

    def form_valid(self, form):
        self.object = form.save()
        return super().form_valid(form)

    # def get_success_url(self) -> str:
    #     return reverse_lazy("accounts:client-profile", kwargs={"pk": self.object.pk})


# Vendor views
class VendorSignUpView(SuccessMessageMixin, CreateView):
    model = User
    form_class = VendorCreationForm
    template_name = "registration/signup_form.html"
    success_message = "Account Created Successfully"

    def get_context_data(self, **kwargs):
        kwargs["user_type"] = "vendor"
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect("accounts:dashboard")


class VendorDetailView(LoginRequiredMixin, DetailView):
    model = Vendor
    template_name = "accounts/user_profile.html"
    context_object_name = "vendor_detail"

    def get_queryset(self):
        return Vendor.objects.filter(user=self.request.user)


class VendorUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Vendor
    template_name = "accounts/user_update.html"
    success_message = "Profile Updated Successfully!"
    fields = [
        "image",
        "phone_number",
        "shop_location",
    ]
    success_url = reverse_lazy("accounts:dashboard")

    def get_queryset(self):
        return Vendor.objects.filter(user=self.request.user)

    def form_valid(self, form):
        self.object = form.save()
        return super().form_valid(form)

    # def get_success_url(self) -> str:
    #     return super().get_success_url() or reverse_lazy(
    #         "accounts:vendor-profile", kwargs={"pk": self.object.pk}
    #     )


# Admin Views
class AdminSignUpView(SuccessMessageMixin, CreateView):
    model = User
    form_class = AdminCreationForm
    template_name = "registration/signup_form.html"
    success_message = "Account Created Successfully"

    def get_context_data(self, **kwargs):
        kwargs["user_type"] = "admin"
        return super().get_context_data(**kwargs)

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect("accounts:dashboard")


class AdminDetailView(LoginRequiredMixin, DetailView):
    model = Admin
    template_name = "accounts/user_profile.html"

    def get_queryset(self):
        return Admin.objects.filter(user=self.request.user)


class AdminUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Admin
    fields = ["image"]
    template_name = "accounts/user_update.html"
    success_message = "Profile Updated Successfully!"

    def get_queryset(self):
        return Admin.objects.filter(user=self.request.user)

    def form_valid(self, form):
        self.object = form.save()
        return super().form_valid(form)

    def get_success_url(self) -> str:
        return reverse_lazy("accounts:admin-profile", kwargs={"pk": self.object.pk})

accounts/templates/accounts/dashboard.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Dashboard{% endblock %}

{% block content %}
<div class="container-fluid bg-secondary-subtle">
    {% if user.is_client %}
    <section class="py-3">
        <div class="row">

            <!-- CLIENT PROFILE AREA -->
            <div class="col-md-3 col-sm-12 border-end border-dark-subtle mb-3">    
                <div class="card mb-2 rounded-0">
                    <h4 class="card-header fw-bold">
                        Profile Details
                    </h4>
                    {% for client in client_profile %}
                    <div class="card-body">
                        {% if client.image %}
                        <img src="{{profile.image.url}}" alt="" class="avatarimg mb-3">
                        {% else %}
                        <img src="https://images.unsplash.com/photo-1634926878768-2a5b3c42f139?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTV8fGF2YXRhcnxlbnwwfHwwfHx8MA%3D%3D"
                            alt="" class="avatarimg mb-3">
                        {% endif %}
                        {% if not client.phone_number or not client.location %}
                        <p class="card-text">Update Personal Information</p>
                        <a href="{%url 'accounts:client-update' user.id %}">Update</a>
                        {% else %}
                        <p class="card-text">{{client.phone_number}}</p>
                        <p class="card-text">{{client.location}}</p>
                        <a href="{%url 'accounts:client-update' user.id %}" class="btn btn-sm btn-outline-info">Update</a>
                        {% endif %}
                    </div>
                    {% endfor %}
                </div>
            </div>

            <!-- GAS SUPPLIERS LIST -->
            <div class="col-md-9 col-sm-12 mb-3">
                <section class="card rounded-0">
                    <h4 class="card-header fw-bold">
                        Gas Suppliers
                    </h4>
                    <div class="card-body">
                        {% if client_products %}
                            <div class="table-responsive">
                                <table class="table">
                                    <thead>
                                        <tr>
                                            <th>Image</th>
                                            <th>Name</th>
                                            <th>Mass</th>
                                            <th>Price</th>
                                            <th>Shop</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for product in client_products %}
                                        <tr>
                                            <td>
                                                <img src="{{product.product_image.url}}" class="dash-image" alt="">
                                            </td>
                                            <td>{{product.name}}</td>
                                            <td>{{product.mass}}</td>
                                            <td>{{product.price}}</td>
                                            <td>{{product.shop}} - {{product.shop_contact}}</td>
                                            <td>
                                                <a href="{% url 'shop:create-order' product.id %}" class="btn-sm btn btn-outline-success">Order</a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        {% else %}
                        <p class="text-center bg-info p-3 fw-bold rounded">No Gas Suppliers</p>
                        {% endif %}
                    </div>
                </section>
                
            </div>

        </div>
    </section>
    {% endif %}
    
    {% if user.is_vendor %}
    <section class="py-3">
        <div class="row">

            <!-- PROFILE AREA -->
            <div class="col-md-3 col-sm-12 border-end border-dark-subtle mb-3">                
                <div>
                    <div class="card mb-2 rounded-0">
                        <h4 class="card-header fw-bold">
                            Shop Details
                        </h4>
                        {% for shop in vendor_shop %}
                        <div class="card-body">
                            {% if shop.image %}
                            <img src="{{shop.image.url}}" alt="" class="shopimage mb-3">
                            {% else %}
                            <img src="https://images.unsplash.com/photo-1632224120632-895c7132d2b1?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MTl8fGdhcyUyMHN0YXRpb258ZW58MHx8MHx8fDA%3D"
                                alt="" class="shopimage mb-3">
                            {% endif %}
                            {% if not shop.name or not shop.location or not shop.contact %}
                            <p class="card-text">Update Shop Information</p>
                            <a href="{%url 'shop:shop-update' shop.id %}">Update</a>
                            {% else %}
                            <p class="card-text"><strong>Name: </strong>{{shop.name}}</p>
                            <p class="card-text"><strong>Contact: </strong>{{shop.contact}}</p>
                            <p class="card-text"><strong>Location: </strong>{{shop.location}}</p>
                            <a href="{%url 'shop:shop-update' shop.id %}" class="btn btn-outline-dark btn-sm">Update</a>
                            {% endif %}
                        </div>
                        {% endfor %}
                    </div>
                </div>
            </div>

            <!-- DASHBOARD AREA -->
            <div class="col-md-9 col-sm-12 mb-3">
                <section class="card rounded-0">
                    <h4 class="fw-bold card-header">Dashboard</h4>
                    <div class="card-body">
                        <!-- Products side -->
                        <div class="mb-3">
                            <div class="d-flex justify-content-between align-items-center">
                                <div>
                                    <h6 class="fw-bold card-title">Products</h6>
                                </div>
                                <div>
                                    <a class="btn btn-success" href="{%url 'shop:product-create'%}"><i class="bi bi-plus-lg"></i></a>
                                </div>
                            </div>
                            <hr>
                            {% for shop in vendor_shop %}
                            {% if not shop.name or not shop.location or not shop.contact %}
                            <p class="bg-warning p-3 fw-bold">Update your shop details <a href="{%url 'shop:shop-update' shop.id %}">here</a> to
                                continue</p>
                            {% else %}
                            {% if vendor_product %}
                            <div class="table-responsive">
                                <table class="table table-bordered">
                                    <thead>
                                        <tr>
                                            <th>Image</th>
                                            <th>Name</th>
                                            <th>Mass</th>
                                            <th>Price</th>
                                            <th>Availability</th>
                                            <th>Shop</th>
                                            <th>Shop Phone</th>
                                            <th>Actions</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        {% for product in vendor_product %}
                                        <tr>
                                            <td>
                                                <img src="{{product.product_image.url}}" class="dash-image" alt="">
                                            </td>
                                            <td>{{product.name}}</td>
                                            <td>{{product.mass}}</td>
                                            <td>{{product.price}}</td>
                                            <td>{{product.availability}}</td>
                                            <td>{{product.shop}}</td>
                                            <td>{{product.shop_contact}}</td>
                                            <td><a href="{% url 'shop:product-update' product.id %}" class="btn-sm btn btn-outline-primary">Update</a>
                                                <a href="{% url 'shop:product-delete' product.id%}" class="btn-sm btn btn-outline-danger">Delete</a>
                                            </td>
                                        </tr>
                                        {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                        
                            {% else %}
                            <p class="bg-info p-3 fw-bold">Create a product <a href="{%url 'shop:product-create'%}">here</a></p>
                            {% endif %}
                            {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                </section>
            </div>
        </div>
    </section>
    {% endif %}
</div>
{% endblock %}

accounts/templates/accounts/user_update.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Update Profile{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
{% if user.is_vendor %}
<section class="container mb-3 py-3 px-3">
    <form method="post" class="p-4 border rounded-3 bg-body-tertiary" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-floating mb-3">
            {{ form.image|as_crispy_field }}
        </div>
        <div class="form-floating mb-3">
            {{ form.phone_number|as_crispy_field }}
        </div>
        <div class="form-floating mb-3">
            {{ form.shop_location|as_crispy_field }}
        </div>
        <button class="btn btn-dark" type="submit">Update</button>
    </form>
</section>
{% endif %}

{% if user.is_client %}
<section class="container mb-3 py-3 px-3">
    <form method="post" class="p-4 border rounded-3 bg-body-tertiary" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-floating mb-3">
            {{ form.image|as_crispy_field }}
        </div>
        <div class="form-floating mb-3">
            {{ form.phone_number|as_crispy_field }}
        </div>
        <div class="form-floating mb-3">
            {{ form.location|as_crispy_field }}
        </div>
        <button class="btn btn-dark" type="submit">Update</button>
    </form>
</section>
{% endif %}
{% endblock %}