accounts/urls.py
from django.urls import path

from accounts.views import (
    ClientSignUpView,
    ClientDetailView,
    ClientUpdateView,
    VendorDetailView,
    VendorUpdateView,
    VendorSignUpView,
    AdminSignUpView,
    AdminDetailView,
    AdminUpdateView,
    dashboard,
    SignUpView,
    UserListView,
    UserDetailView,
)

app_name = "accounts"

urlpatterns = [
    path("dashboard/", dashboard, name="dashboard"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("detail/<str:pk>/", UserDetailView.as_view(), name="user-detail"),
    # client urls
    path("sign-up/client/", ClientSignUpView.as_view(), name="client-signup"),
    path("profile/<str:pk>/client/", ClientDetailView.as_view(), name="client-profile"),
    path("update/<str:pk>/client/", ClientUpdateView.as_view(), name="client-update"),
    # vendor urls
    path("sign-up/vendor/", VendorSignUpView.as_view(), name="vendor-signup"),
    path("profile/<str:pk>/vendor/", VendorDetailView.as_view(), name="vendor-profile"),
    path("update/<str:pk>/vendor/", VendorUpdateView.as_view(), name="vendor-update"),
    # admin urls
    path("signup/admin/", AdminSignUpView.as_view(), name="admin-signup"),
    path("profile/<str:pk>/admin/", AdminDetailView.as_view(), name="admin-profile"),
    path("update/<str:pk>/admin/", AdminUpdateView.as_view(), name="admin-update"),
]

gasdelivery/urls.py
from django.contrib import admin
from django.urls import path, include
from accounts.views import landing

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("shop/", include("shop.urls")),
    path("", landing, name="landing"),
]

shop/urls.py
from django.urls import path

from shop.views import (
    ShopUpdateView,
    ShopDetailView,
    ShopListView,
    ProductDetailView,
    ProductCreateView,
    ProductListView,
    ProductUpdateView,
    ProductDeleteView,
    OrderCreateView,
    VendorOrderListView,
    ClientOrderListView,
)

app_name = "shop"

urlpatterns = [
    path("shops/", ShopListView.as_view(), name="shop-update"),
    path("update/<str:pk>/shop/", ShopUpdateView.as_view(), name="shop-update"),
    path("detail/<str:pk>/shop/", ShopDetailView.as_view(), name="shop-detail"),
    path("create/", ProductCreateView.as_view(), name="product-create"),
    path(
        "product/<str:pk>/detail/", ProductDetailView.as_view(), name="product-detail"
    ),
    path(
        "product/<str:pk>/update/", ProductUpdateView.as_view(), name="product-update"
    ),
    path(
        "product/<str:pk>/delete/", ProductDeleteView.as_view(), name="product-delete"
    ),
    path("products/", ProductListView.as_view(), name="product-list"),
    path("order/<str:pk>/", OrderCreateView.as_view(), name="create-order"),
    path("orders/", VendorOrderListView.as_view(), name="order-list"),
    path("orders/client/", ClientOrderListView.as_view(), name="client-orders"),
]

gasdelivery/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}{% endblock %} | Dial-a-Gas</title>
        <link rel="stylesheet" href="{% static 'css/styles.css' %}">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    </head>

    <body>
        <nav class="navbar mynav navbar-expand-md sticky-top px-2 bg-secondary-subtle border-dark-subtle border-bottom">
            <div class="container-fluid">
                <h6 class="navbar-brand fw-bold">
                    Dial-a-Gas
                </h6>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#collapsibleNavbar">
                    <span class="navbar-toggler-icon"></span>
                </button>
            </div>
            <div class="collapse navbar-collapse justify-content-end" id="collapsibleNavbar">
                <ul class="navbar-nav">
                    {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'accounts:dashboard' %}">Dashboard</a>
                    </li>
                    <li class="nav-item">
                        <p class="nav-link">{{user.get_short_name}}</p>
                    </li>
                    {% if user.is_client %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shop:client-orders' %}">Orders</a>
                    </li>
                    {% endif %}
                    {% if user.is_vendor %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'shop:order-list' %}">Orders</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{%url 'accounts:vendor-update' user.id %}">Profile</a>
                    </li>
                    {% endif %}
                    <li class="nav-item">
                        <form method="post" action="{% url 'logout' %}">
                            {% csrf_token %}
                        <button type="submit" class="btn btn-sm btn-outline-danger p-2 rounded">Logout</button>
                        </form>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link btn rounded bg-info" href="{% url 'login' %}">Login</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        <div class="container-fluid bg-secondary-subtle mb-0 mx-0 my-0 px-0 py-0">
            <div class="container">
                {% if messages %}
                <div id="message-toast" class="position-fixed top-0 end-0 p-3 mt-5" style="z-index: 5">
                    {% for message in messages %}
                    <div class="toast show {% if message.tags == 'error' %}bg-danger{% else %}bg-success{% endif %}"
                        role="alert" aria-live="assertive" aria-atomic="true">
                        <div class="toast-header">
                            <strong class="me-auto">Notification</strong>
                            <button type="button" class="btn-close" data-bs-dismiss="toast" aria-label="Close"></button>
                        </div>
                        <div class="toast-body">
                            {{ message }}
                        </div>
                    </div>
                    {% endfor %}
                </div>

                <script>
                    var toastElList = [].slice.call(document.querySelectorAll('.toast'))
                    var toastList = toastElList.map(function (toastEl) {
                        return new bootstrap.Toast(toastEl)
                    });

                    toastList.forEach(toast => toast.show());
                </script>
                {% endif %}
            </div>
            {% block content %}
            {% endblock %}
            <hr>
            <footer class="py-3">
                <div class="text-center text-secondary">
                    <p>Dial-a-Gas<br>
                        Get your gas delivered at your doorstep
                    </p>
                </div>
            </footer>
        </div>
        
        {% block scripts %}
        {% endblock %}
        <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"></script>
    </body>

</html>

gasdelivery/templates/index.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Welcome{% endblock %}

{% load crispy_forms_tags %}

{% block content %}{% endblock %}

gasdelivery/templates/landing.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Welcome{% endblock %}

{% block content %}
<div class="container py-3">
    <h2 class="fw-bold text-center">
        Hello
    </h2>
    {% if user.is_authenticated %}
    <p class="text-center">Welcome, {{user.get_username}}</p>
    <div class="text-center">
        <a href="{% url 'accounts:dashboard' %}" class="btn btn-info mt-3">Dashboard</a>
    </div>
    {% else %}
    <div class="text-center">
        <a href="{% url 'accounts:signup' %}" class="btn btn-success mt-3">Sign Up</a>
        <a href="{% url 'login' %}" class="btn btn-info mt-3">Sign In</a>
    </div>
    {% endif %}
</div>
{% endblock %}